ARG PYTHON_VERSION=3.10
ARG UV_VERSION=0.12.17
ARG CUDA_VERSION=12.6.1-base-ubuntu24.04

FROM ghcr.io/astral-sh/uv:$UV_VERSION AS uv

FROM nvidia/cuda:$CUDA_VERSION
ARG PYTHON_VERSION

ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && \
    apt-get install --no-install-recommends -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
    python$PYTHON_VERSION \
    python$PYTHON_VERSION-dev \
    git vim curl gdb ca-certificates gnupg2 tar make gcc libssl-dev zlib1g-dev libncurses5-dev \
    libbz2-dev libreadline-dev libreadline6-dev libxml2-dev xz-utils libgdbm-dev libgdbm-compat-dev tk-dev dirmngr \
    libxmlsec1-dev libsqlite3-dev libffi-dev liblzma-dev lzma lzma-dev uuid-dev && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python$PYTHON_VERSION

# make some useful symlinks that are expected to exist
RUN ln -sfn /usr/bin/python${PYTHON_VERSION} /usr/bin/python3  & \
    ln -sfn /usr/bin/python${PYTHON_VERSION} /usr/bin/python

COPY --from=uv /uv /uvx /bin/

# Install python packages
RUN pip install -U pip setuptools \
    && pip install black pipenv virtualenv clearml \
    && pip install cffi

COPY ./.devcontainer/clearml.conf /root/clearml.conf

ENV EFLOMAL_PATH=/workspaces/machine.py/.venv/lib/python${PYTHON_VERSION}/site-packages/eflomal/bin

CMD ["bash"]
